name: Update Website

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  deploy-site:
    name: "Deploy Website"
    if: ${{ github.ref == 'refs/heads/gh-pages' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages
      - name: "SFTP Deploy"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "${{ secrets.SFTP_HOST }}"
          remote-user: "${{ secrets.SFTP_USER }}"
          remote-password: "${{ secrets.SFTP_PASSWORD }}"
          remote-path: "/www/htdocs/go"
